name: Test

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  BUILD_TARGET: Sep4IotDeviceTests
  APPEUI: ${{secrets.LORA_appEUI}}
  APPKEY: ${{secrets.LORA_appKEY}}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Init LoRa
      run: cd ${{github.workspace}}/scripts &&
         chmod +x init_lora.sh &&
         bash init_lora.sh $APPEUI $APPKEY
      shell: bash

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{env.BUILD_TARGET}}

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ./Sep4IotDeviceTests

