name: PlatformIO CI

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            ./modules
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Deploy Project to TestDevice
        run: pio remote run -e linux --target upload --verbose
